name: publish doc
on:
  push:
    branches:
      - main
  # run manually from Actions tab
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    if: >
      !contains(github.event.head_commit.message, 'skip-deploy')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.5"
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Cache Poetry dev dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Configure Poetry (no virtualenvs)
        run: |
          poetry config virtualenvs.create false
      - name: Install development dependencies for docgen
        run: |
          poetry install --no-interaction --no-ansi --only dev
      - name: deploy doc
        run: mkdocs gh-deploy --force
