name: pre-commit

on: push

jobs:
  pre-commit:
    if: >
      !contains(github.event.head_commit.message, 'skip-ci')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: [3.10.13, 3.11.5]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Cache Poetry dev dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Configure Poetry (no virtualenvs)
        run: |
          poetry config virtualenvs.create false
      - name: Install development dependencies for docgen
        run: |
          poetry install --no-interaction --no-ansi --only dev
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0
